gym/urls.py
from django.urls import path
from gym import views

# Create your views here.
urlpatterns =[
    path('',views.home,name='Inicio'),
    # Read de los modelos
    path('profesor', views.Profesor, name='Profesor'),
    path('clase', views.Clase, name='Clase'),
    path('estudiante', views.Estudiante, name='Estudiante'),
    # Create de los modelos
    path('profesor/formulario',views.formProfesor,name='formProfesores'),
    path('clase/formulario',views.formClase,name='formClase'),
    path('estudiante/formulario',views.formEstudiantes,name='formEstudiantes'),
    # Delete de los modelos
    path('profesor/eliminar<nombre>',views.eliminarProfesor,name='eliminarProfe'),
    path('clase/eliminar<profesor>',views.eliminarClases,name='eliminarClase'),
    path('estudiante/eliminar<apellido>',views.eliminarEstudiante,name='eliminarEstu'),
    # Update de los modelos
    path('profesor/editar<nombre>',views.editarProfesor,name='editarProfesor'),
    path('clase/editar<profesor>',views.editarClase,name='editarClase'),
    path('estudiante/editar<correo>',views.editarEstudiante,name='editarEstudiante')
]

page/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gym.urls'))
]

gym/models.py
from django.db import models

# Create your models here.
class Estudiantes(models.Model):
    nombre = models.CharField(max_length=40)
    apellido = models.CharField(max_length=40)
    correo = models.EmailField()
    pase = models.CharField(max_length=30)
    documento = models.IntegerField()
    fecha = models.DateField()

    def __str__(self):
        return f'Nombre: {self.nombre} - Apellido: {self.apellido} - Correo: {self.correo} - Pase: {self.pase} - Documento: {self.documento}'


class Profesores(models.Model):
    nombre = models.CharField(max_length=40)
    apellido = models.CharField(max_length=40)
    correo = models.EmailField()
    documento = models.IntegerField()

    def __str__(self):
        return f'Nombre: {self.nombre} - Apellido: {self.apellido} - Correo: {self.correo} - DNI: {self.documento}'


class Clases(models.Model):
    nombre = models.CharField(max_length=40)
    profesor = models.CharField(max_length=40)
    dias = models.CharField(max_length=40)
    horario = models.CharField(max_length=40)

    def __str__(self):
        return f'Nombre:{self.nombre} - Profesor: {self.profesor} - Dias: {self.dias} - Horario: {self.horario}'

gym/forms.py
from django import forms

class FormProfesores(forms.Form):
    nombre = forms.CharField(max_length=40)
    apellido = forms.CharField(max_length=40)
    correo = forms.EmailField()
    documento = forms.IntegerField()

class FormClase(forms.Form):
    nombre = forms.CharField(max_length=40)
    profesor = forms.CharField(max_length=40)
    dias = forms.CharField(max_length=40)
    horario = forms.CharField(max_length=40)

class FormEstudiante(forms.Form):
    nombre = forms.CharField(max_length=40)
    apellido = forms.CharField(max_length=40)
    correo = forms.EmailField()
    pase = forms.CharField(max_length=30)
    documento = forms.IntegerField()
    fecha = forms.DateField()

gym/views.py
from django.shortcuts import render, HttpResponse,redirect
from .models import Profesores, Clases, Estudiantes
from .forms import FormProfesores, FormClase, FormEstudiante

def home(request):
    return render(request,'gym/home.html')


# Read de los modelos

def Profesor(request):    
    profesores = Profesores.objects.all()
    return render(request, 'gym/modelos/profesores.html', {'profesores':profesores})

def Clase(request):
    clases = Clases.objects.all()
    return render(request, 'gym/modelos/clases.html', {'clases':clases})

def Estudiante(request):
    estudiantes = Estudiantes.objects.all()
    return render(request, 'gym/modelos/estudiantes.html', {'estudiantes':estudiantes})

# Create de los modelos 

def formProfesor(request):
    if request.method == 'POST':
        formulario = FormProfesores(request.POST)
        print(formulario)
        if formulario.is_valid:
            informacion = formulario.cleaned_data
            profesor = Profesores(nombre = informacion['nombre'],apellido = informacion['apellido'],correo = informacion['correo'],documento = informacion['documento']) # type: ignore
            profesor.save()
            return redirect('Profesor')
    else:
        formulario = FormProfesores()

    return render(request,'gym/formularios/formProfesores.html', {'formulario':formulario})

def formClase(request):
    if request.method == 'POST':
        formulario = FormClase(request.POST)
        print(formulario)
        if formulario.is_valid:
            informacion = formulario.cleaned_data
            clase = Clases(nombre = informacion['nombre'],profesor = informacion['profesor'],dias = informacion['dias'],horario = informacion['horario']) # type: ignore
            clase.save()
            return redirect('Clase')
    else:
        formulario = FormClase()

    return render(request,'gym/formularios/formClase.html', {'formulario':formulario}) 

def formEstudiantes(request):
    if request.method == 'POST':
        formulario = FormEstudiante(request.POST)
        print(formulario)
        if formulario.is_valid:
            informacion = formulario.cleaned_data
            estudiante = Estudiantes(nombre = informacion['nombre'],apellido = informacion['apellido'],correo = informacion['correo'],pase = informacion['pase'],documento = informacion['documento'],fecha = informacion['fecha'])
            estudiante.save()
            return redirect('Estudiante')
    else:
        formulario = FormEstudiante()

    return render(request,'gym/formularios/formEstudiante.html', {'formulario':formulario})

# Delete de los modelos 

def eliminarProfesor(request,nombre):
    profesor = Profesores.objects.get(nombre=nombre)
    profesor.delete()
    return redirect('Profesor')

def eliminarClases(request,profesor):
    clase = Clases.objects.get(profesor=profesor)
    clase.delete()
    return redirect('Clase')

def eliminarEstudiante(request,apellido):
    estudiante = Estudiantes.objects.get(apellido=apellido)
    estudiante.delete()
    return redirect('Estudiante')

# Update de los modelos

def editarProfesor(request,nombre):

    profesor = Profesores.objects.get(nombre=nombre)

    if request.method == 'POST':

        miformulario = FormProfesores(request.POST)
        print(miformulario)

        if miformulario.is_valid:

            informacion = miformulario.cleaned_data
            profesor.nombre = informacion['nombre']
            profesor.apellido = informacion['apellido']
            profesor.documento = informacion['documento']
            profesor.correo = informacion['correo']
            profesor.save()

            return redirect('Profesor')
    
    else:
        miformulario = FormProfesores(initial={'nombre':profesor.nombre,'apellido':profesor.apellido,'documento':profesor.documento,'correo':profesor.correo})
    
    return render(request,'gym/editar/editarProfesor.html',{'miformulario':miformulario,'profesor':profesor})


def editarClase(request,profesor):

    clase = Clases.objects.get(profesor=profesor)

    if request.method == 'POST':

        miformulario = FormClase(request.POST)
        print(miformulario)

        if miformulario.is_valid:

            informacion = miformulario.cleaned_data
            clase.nombre = informacion['nombre']
            clase.profesor = informacion['profesor']
            clase.dias = informacion['dias']
            clase.horario = informacion['horario']
            clase.save()

            return redirect('Clase')
    
    else:
        miformulario = FormClase(initial={'nombre':clase.nombre,'profesor':clase.profesor,'dias':clase.dias,'horario':clase.horario})
    
    return render(request,'gym/editar/editarClase.html',{'miformulario':miformulario,'clase':clase})


def editarEstudiante(request,correo):

    estudiante = Estudiantes.objects.get(correo=correo)

    if request.method == 'POST':

        miformulario = FormEstudiante(request.POST)
        print(miformulario)

        if miformulario.is_valid:

            informacion = miformulario.cleaned_data
            estudiante.nombre = informacion['nombre']
            estudiante.apellido = informacion['apellido']
            estudiante.correo = informacion['correo']
            estudiante.pase = informacion['pase']
            estudiante.documento = informacion['documento']
            estudiante.fecha = informacion['fecha']
            estudiante.save()

            return redirect('Estudiante')
    
    else:
        miformulario = FormEstudiante(initial={'nombre':estudiante.nombre,'apellido':estudiante.apellido,'correo':estudiante.correo,'pase':estudiante.pase,'documento':estudiante.documento,'fecha':estudiante.fecha})
    
    return render(request,'gym/editar/editarEstudiante.html',{'miformulario':miformulario,'estudiante':estudiante})

gym/templates/gym/formularios/formClase.html
{% extends "gym/indexform.html" %}
		{% load static %}
{% block contenidoQueCambia %}
    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
            <a class="btn text-light" href="{% url 'Clase' %}">Volver</a>
        </div>
    </nav>
    <section class=" d-flex flex-column align-items-center w-100">
        <div class="m-4">
            <h1 class="text-light text-uppercase fw-bold">Agregar Clase</h1>
        </div>
        <form action="" method="POST" class="w-50 mt-3">
            {% csrf_token %}
            <div class="d-flex flex-column gap-2">
                <div class="col-md">
                    <div class="form-floating">
                        <input type="text" name="nombre" maxlength="40" required id="id_nombre" class="form-control">
                        <label for="id_nombre">Nombre</label>
                    </div>
                </div>
                <div class="col-md">
                    <div class="form-floating">
                        <input type="text" name="profesor" maxlength="40" required id="id_profesor" class="form-control">
                        <label for="id_profesor">Profesor</label>
                    </div>
                </div>
                <div class="col-md">
                    <div class="form-floating">
                        <input type="text" name="dias" maxlength="40" required id="id_dias" class="form-control">
                        <label for="id_dias">Dias</label>
                    </div>
                </div>
                <div class="col-md">
                    <div class="form-floating">
                        <input type="text" name="horario" maxlength="40" required id="id_horario" class="form-control">
                        <label for="id_horario">Horario</label>
                    </div>
                </div>
            </div>

            <input type="submit" value="Enviar" class="btn btn-primary btn-lg mt-3">
        </form>
    </section>

{% endblock %}

gym/templates/gym/formularios/formEstudiante.html
{% extends "gym/indexform.html" %}
		{% load static %}
{% block contenidoQueCambia %}
    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
            <a class="btn text-light" href="{% url 'Estudiante' %}">Volver</a>
        </div>
    </nav>
    <section class=" d-flex flex-column align-items-center w-100">
        <div class="mt-3">
            <h1 class="text-light text-uppercase fw-bold">Agregar Alumno</h1>
        </div>
        <form action="" method="POST" class="w-50 mt-3">
            {% csrf_token %}
            <div class="d-flex flex-column gap-2">
                <div class="col-md">
                    <div class="form-floating">
                        <input type="text" name="nombre" maxlength="40" required id="id_nombre" class="form-control">
                        <label for="id_nombre">Nombre</label>
                    </div>
                </div>
                <div class="col-md">
                    <div class="form-floating">
                        <input type="text" name="apellido" maxlength="40" required="" id="id_apellido" class="form-control">
                        <label for="id_apellido">Apellido</label>
                    </div>
                </div>
                <div class="col-md">
                    <div class="form-floating">
                        <input type="email" name="correo" required id="id_correo" class="form-control">
                        <label for="id_correo">Correo</label>
                    </div>
                </div>
                <div class="col-md">
                    <div class="form-floating">
                        <input type="text" name="pase" maxlength="30" required id="id_pase" class="form-control">
                        <label for="id_pase">Pase</label>
                    </div>
                </div>
                <div class="col-md">
                    <div class="form-floating">
                        <input type="number" name="documento" required id="id_documento" class="form-control">
                        <label for="id_documento">Documento</label>
                    </div>
                </div>
                <div class="col-md">
                    <div class="form-floating">
                        <input type="text" name="fecha" required id="id_fecha" class="form-control">
                        <label for="id_fecha">Fecha (YY-MM-DD)</label>
                    </div>
                </div>
            </div>

            <p>

                
                
                  
                
              </p>
            <input type="submit" value="Enviar" class="btn btn-primary btn-lg mt-3">
        </form>
    </section>

{% endblock %}

gym/templates/gym/formularios/formProfesores.html
{% extends "gym/indexform.html" %}
		{% load static %}
{% block contenidoQueCambia %}
    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
            <a class="btn text-light" href="{% url 'Profesor' %}">Volver</a>
        </div>
    </nav>
    <section class=" d-flex flex-column align-items-center w-100">
        <div class="mt-3">
            <h1 class="text-light text-uppercase fw-bold">Agregar Profesor</h1>
        </div>
        <form action="" method="POST" class="w-50 mt-3">
            {% csrf_token %}
            <div class="d-flex flex-column gap-2">
                <div class="col-md">
                    <div class="form-floating">
                        <input type="text" name="nombre" maxlength="40" required id="id_nombre" class="form-control">
                        <label for="id_nombre">Nombre</label>
                    </div>
                </div>
                <div class="col-md">
                    <div class="form-floating">
                        <input type="text" name="apellido" maxlength="40" required="" id="id_apellido" class="form-control">    
                        <label for="id_apellido">Apellido</label>
                    </div>
                </div>
                <div class="col-md">
                    <div class="form-floating">
                        <input type="email" name="correo" required="" id="id_correo" class="form-control">
                        <label for="id_correo">Correo</label>
                    </div>
                </div>
                <div class="col-md">
                    <div class="form-floating">
                        <input type="number" name="documento" required="" id="id_documento" class="form-control">
                        <label for="id_documento">Documento:</label>
                    </div>
                </div>
            </div>

            <input type="submit" value="Enviar" class="btn btn-primary btn-lg mt-3">
        </form>
    </section>

{% endblock %}